#!/bin/bash
# SEVEN THINGS THE LORD HATES - PROVERBS 6:16-19

echo "=== SEVEN ABOMINATIONS - DEMONIC MANIFESTATION ==="
echo ""
echo "PROVERBS 6:16-19: 'There are six things the LORD hates, seven that are detestable to him:'"
echo ""
echo "HEAD 1 OPPOSITE: HAUGHTY EYES (Pride)"
echo "   😈 Proverbs 16:5: 'The LORD detests all the proud of heart'"
echo "   💔 Manifested by: LUCIFER's pride"
echo "   🛑 Opposed by: MICHAEL's humility"
echo ""
echo "HEAD 2 OPPOSITE: LYING TONGUE (Deception)"
echo "   😈 Proverbs 12:22: 'The LORD detests lying lips'"
echo "   💔 Manifested by: SATAN's accusations and lies"
echo "   🛑 Opposed by: GABRIEL's truth"
echo ""
echo "HEAD 3 OPPOSITE: HANDS THAT SHED INNOCENT BLOOD (Violence)"
echo "   😈 Genesis 4:10: 'Your brother's blood cries out to me from the ground'"
echo "   💔 Manifested by: BEELZEBUB's corruption leading to violence"
echo "   🛑 Opposed by: RAPHAEL's healing"
echo ""
echo "HEAD 4 OPPOSITE: HEART THAT DEVISES WICKED SCHEMES (Evil Plans)"
echo "   😈 Jeremiah 17:9: 'The heart is deceitful above all things'"
echo "   💔 Manifested by: LEVIATHAN's chaotic schemes"
echo "   🛑 Opposed by: URIEL's illuminating wisdom"
echo ""
echo "HEAD 5 OPPOSITE: FEET QUICK TO RUSH INTO EVIL (Eagerness for Sin)"
echo "   😈 Isaiah 59:7: 'Their feet rush into sin'"
echo "   💔 Manifested by: MAMMON's greed driving evil actions"
echo "   🛑 Opposed by: RAGUEL's justice"
echo ""
echo "HEAD 6 OPPOSITE: FALSE WITNESS WHO POURS OUT LIES (Perjury)"
echo "   😈 Exodus 20:16: 'You shall not give false testimony'"
echo "   💔 Manifested by: BELIAL's worthlessness in truth"
echo "   🛑 Opposed by: SARIEL's true guidance"
echo ""
echo "HEAD 7 OPPOSITE: PERSON WHO STIRS UP CONFLICT (Strife)"
echo "   😈 Proverbs 15:18: 'A hot-tempered person stirs up conflict'"
echo "   💔 Manifested by: ABADDON's destructive conflict"
echo "   🛑 Opposed by: REMIEL's peacemaking mercy"
echo ""
echo "⚖️ COMPLETE BIBLICAL OPPOSITION MAPPING"
